test:
  script:
  - apt-get update -qy
  - apt-get -y install python3-pip python-dev
  # - pip3 install -U setuptools
  # - python3 -m venv virtual
  # - source virtual/bin/activate
  - pip3 install -r requirements.txt
  - python3 -m pytest --cov app/ --cov-report term --cov-report html
