test:
  script:
  - apt-get update -qy
  - apt-get -y install python3-pip python-dev
  - pip3 install -U setuptools
  - python3 -m venv virtual
  - source virtual/bin/activate
  - pip install -r requirements.txt
  - python -m pytest --cov-report html --cov app/api/
