python:
  - "3.6"
before_install:
  - apt-get -y install python3-pip python-dev
  - pip3 install -U setuptools
  - python3 -m venv virtual
  - source virtual/bin/activate
install:
  - pip3 install -r requirements.txt
test:
  - python3 -m pytest --cov-report html --cov app/api/
